### ISSUE TITLE
Adding publication to multiple series / config issue

### ISSUE THREAD

**Issue by monicapatel21** [wri/wri_sites#106]
here is that config page: https://cop27-wriflagship.pantheonsite.io/admin/structure/types/manage/publication/fields/node.publication.field_publication_series/storage

## TODO:
- [x] Sorting should be based on the name of the Series. Right now it's based on the series ID, which is pretty oblique (newest first)

## Testing instructions
- [ ] On https://develop-wriflagship.pantheonsite.io/admin/content?title=&type=publication&status=All&langcode=All&uid= find a publication and view it
- [ ] See the "In this series" section of the page, if you're on a page with that set. If you're not, you should not see that section.
- [ ] Edit the publication. See that you can add multiple Series under "Related" -> "Publication Series" 
- [ ] Add  a few more series values
- [ ] See that there are multiple Series showing up under "In this series" on the front end.
- [ ] Click through a few of those links under "In this series" and  make sure you see this node linked back.
- [ ] Also review both the publication and an article on mobile to compare the dropdown between how it work with "More on" and "In This Series". They should be functionally pretty much the same. Here's a good "More on" article: https://develop-wriflagship.pantheonsite.io/insights/which-electric-school-bus-business-model-right-your-district

**Comment by shannon-paton** [comment]
Publication series page for reference: https://cop27-wriflagship.pantheonsite.io/research/7-transformations-more-equitable-sustainable-cities

**Comment by shannon-paton** [comment]
Hi @monicapatel21 @mariacha moving this to scoping since it would be great to have in time for migrating the [World Resources Report pages](https://www.wri.org/our-work/project/world-resources-report/wrr), which is currently in progress

**Comment by shannon-paton** [comment]
Should be applied to all sites

**Comment by mariacha** [comment]
This is updated at 
https://pr-1002-wriflagship.pantheonsite.io/research/7-transformations-more-equitable-sustainable-cities

There's now a header for each Series. This will also be the case if there's only one series.

I don't think we're communicating that each header is a "Series" very well here. I'm thinking we  could add that "In This Series" header over  each section, maybe change it to "In the Series: Annual Reports" for example.

Here's how that might look
<img width="353" alt="Screen Shot 2023-01-10 at 11 44 12 AM" src="https://user-images.githubusercontent.com/999525/211647463-435beff2-cea7-49bb-a8fe-bcda5354ed46.png">


Original design is here:
https://thinkshout.invisionapp.com/console/WRI-Implementation-Designs--Transferred--ckhgmvcsi034e01aj8214eqoc/ckiqavm6m02hs0154h5g1dv0a/play

So the original design looked like this:
<img width="339" alt="Screen Shot 2023-01-10 at 11 45 11 AM" src="https://user-images.githubusercontent.com/999525/211647673-f7cbf973-1b30-4d18-80cf-2036ac7a7610.png">


Current version of the "In This Series" section is reviewable here:
https://www.wri.org/research/7-transformations-more-equitable-sustainable-cities
<img width="391" alt="Screen Shot 2023-01-10 at 11 36 17 AM" src="https://user-images.githubusercontent.com/999525/211646599-b12341c2-b155-4939-a550-d68005838533.png">

New version, with a header for each "Series" is here:
https://pr-1002-wriflagship.pantheonsite.io/research/7-transformations-more-equitable-sustainable-cities
<img width="344" alt="Screen Shot 2023-01-10 at 11 36 08 AM" src="https://user-images.githubusercontent.com/999525/211646673-21fdb1b9-7e44-48d0-8a1b-4a91447d9adb.png">

**Comment by mariacha** [comment]
Also, the original design collapsed those on mobile: https://thinkshout.invisionapp.com/console/WRI-Implementation-Designs--Transferred--ckhgmvcsi034e01aj8214eqoc/ckiqavm6m02ht0154e7x56s5h/play

I think we just didn't get around to that, or it regressed at some point. This might be a good opportunity to add that back.

@shannon-paton do you have thoughts about the different options? We could probably run this by our design team too, or you could do that on your side. I think what's on https://pr-1002-wriflagship.pantheonsite.io/research/7-transformations-more-equitable-sustainable-cities looks OK but not great. It's possible it just needs someone  with a better  visual eye than I have to make a recommendation on spacing! :)

**Comment by shannon-paton** [comment]
Sorry for the delay here -- would be great to pick this ticket up again for implementation in the next deployment.

Would it be possible to limit the # of reports that display to 10, and then include a link to view more? The view more link could then take you to the resource library to the publications in that series, if that's not too complicated. Otherwise I think the current design would work.

I'm not able to view the original design file with the collapsible option on mobile, could you screenshot or give access @mariacha @monicapatel21 ?

**Comment by mariacha** [comment]
Updated public invision link: https://thinkshout.invisionapp.com/console/share/E9290PEBT3/496883524

TODO here for me: 
Compare how much time/effort it would take to make the mobile version work compared to showing/hiding more than 10 links.

**Comment by mariacha** [comment]
None of the IOs seem to use the Publication Series, so I don't think we need to worry about QAing this on them.

**Comment by wthomaswri** [comment]
Thanks @mariacha. Looping in @shannon-paton

**Comment by shannon-paton** [comment]
Sounds good
