### ISSUE TITLE
Listing Blocks

### ISSUE THREAD

**Issue by monicapatel21** [wri/wri_sites#126]
Currently, on flagship, you can add listing block based on Topic or Subtopic OR based on a Tag, but not based on a Project on the site.

Example, if something is tagged ESBI, you can't create a listing block for it without making a tag. 

Goal: Working session to show Shannon and Wil how to add groupings and show additional view fields.

Follow-up with an hour call with WRI team
 related to  https://github.com/wri/WRIN/issues/379

## TODO:
- [x] Export changes from test - done on https://github.com/wri/wriflagship/pull/988/files
- [x] Add the Project default listing value some way that gets around the content field limit. Idea: build our own tokens that pull from config field patterns.
- [x] Figure out if the Podcast display's contextual filters/argument on the Listing view is overrridden on purpose.

## New backlog ticket
- [x] Default value arguments are getting cumbersome.

**Comment by mariacha** [comment]
You can now add a Listing block and group by a Project. The field has a bunch of disclaimer text about how to deal with the "More" link:
<img width="743" alt="Screenshot 2023-05-23 at 7 20 31 PM" src="https://github.com/wri/wri_sites/assets/999525/39c139f6-c03a-4eec-802b-303194663aaa">

but otherwise should work as you'd expect. I added one to the Electric School Bus page and linked it to the Project resources manually:
https://develop-wriflagship.pantheonsite.io/initiatives/electric-school-bus-initiative

I've also updated the documentation for this block type in the [Content Editor's Guide](https://docs.google.com/document/d/1p7tYALKkEFyWgWQ-MRLMKzMPP_Dlf5WV0Fe2eQM2Fqs/edit#heading=h.61am148l8ktf).

**Comment by wthomaswri** [comment]
Looks good

**Comment by mariacha** [comment]
I tested this out using the Paragraphs on https://www.wri.org/testing-experts-intro-paragraphs to be novel. Moving on to the IOs

**Comment by mariacha** [comment]
This is up on the IOs:

Brasil: TODO

China: TODO

Indonesia: TODO

**Comment by mariacha** [comment]
This is up on the IOs on live. I've added a release notes page on each that tests out this ticket (among others):

Brasil: https://www.wribrasil.org.br/new-features-release-9118

China: https://wri.org.cn/new-features-release-9118

Indonesia: https://wri-indonesia.org/id/new-features-release-9118

Closing this one!
