### ISSUE TITLE
Site upgrades: PHP 8.1

### ISSUE THREAD

**Issue by mariacha** [wri/wri_sites#131]
### Subject of the issue
Right now sites are running php 7.4. Drupal now recommends php 8.x. We like 8.1 over 8.0 because it's easier to develop on our local machines.

### Tasks
- [x] We have some good instructions for upgrading at https://library.thinkshoutlabs.com/articles/upgrade-drupal-site-php-8
- [x] Upgrade one site to php 8.
- [x] Look for php compatibility errors.

**Comment by wthomaswri** [comment]
These look good @mariacha. Only one I wasn't able to replicate is the last one - recaptcha. I think it should be fine but can you check that one out?

**Comment by mariacha** [comment]
I hadn't given very good instructions, and ended up testing  using this method:
Update the Handler for reCaptcha on a webform like https://develop-wriflagship.pantheonsite.io/admin/structure/webform/manage/sign_up_for_wri_digest/handlers to have a tolerance of 100%, then submit the form anonymously at https://develop-wriflagship.pantheonsite.io/subscribe-wri-digest. You should get a warning "There was an error during validation of your form submission, please try to reload the page and submit form again."

That looks good, so moving  over!

**Comment by mariacha** [comment]
I'm seeing an error related to this work on pages like https://www.wri.org/api/reader/node/101313?_format=json that I failed to catch during QA. I'll get that fixed!
