### ISSUE TITLE
SFC error when editing search block

### ISSUE THREAD

**Issue by mariacha** [wri/wri_sites#132]
**Describe the bug**
On pages like [https://live-wri-indonesia.pantheonsite.io/id/admin/structure/block/manage/wrinsearch_2?destination=%2Fid%2Fadmin%2Fstructure%2Fblock](https://live-wri-indonesia.pantheonsite.io/id/admin/structure/block/manage/wrinsearch_2?destination=/id/admin/structure/block) see a WSOD and get the error `Error: Using $this when not in object context in {closure}() (line 39 of /code/web/profiles/contrib/wri_sites/modules/wri_search/components/wri_search_menu.sfc)`

PRobably with the recent sfc upgrade, [the "$this" in the search translation](https://github.com/wri/wri_sites/blob/main/modules/wri_search/components/wri_search_menu.sfc#L39) is no longer going to fly. Let's turn that into a more typical block and eliminate sfc from the equation.

## TODO:
- [x] Existing blocks aren't saving for some reason. Fix that.

## To test
- [ ] Edit the Search form block at https://develop-wriflagship.pantheonsite.io/admin/structure/block/manage/wrinsearch. The changes you make should save correctly and show up on the front end.
- [ ] Note that this also makes the search block translatable (this code has been deployed to Indonesia already)

**Comment by wthomaswri** [comment]
Looks good @mariacha
