### ISSUE TITLE
Paying for Paris - Design QA

### ISSUE THREAD

**Issue by monicapatel21** [wri/wri_sites#210]
This is a meta issue for the design QA on Paying for Paris.

---

# Tasks

- [x] [Navigation 1 / 2](https://github.com/wri/wri_sites/issues/213)
- [x] [Navigation 2 / 2](https://github.com/wri/wri_sites/issues/214)
- [x] [Home Page](https://github.com/wri/wri_sites/issues/216)
- [ ] [Accordion based pages](https://github.com/wri/wri_sites/issues/217)

# Review document
https://docs.google.com/document/d/1LJjQaJZ-J6MFt_4LGphcG9sdf9GPxY7dNxxN5W2FDS0/edit#heading=h.co16wcbalhxu

**Comment by jordankaiser** [comment]
@mariacha Hey just looping you in on the internal QA. Treating this as a meta issue and I'll open individual issues based off the google doc!

**Comment by mariacha** [comment]
The changes here have been merged to develop, so followup QA can happen via https://docs.google.com/document/d/1LJjQaJZ-J6MFt_4LGphcG9sdf9GPxY7dNxxN5W2FDS0/edit#heading=h.prbyyd11rb1a
